import React from 'react';

export const BRAND = {
  primary: "#1E3A5F",
  primaryLight: "#2563A8",
  primarySurface: "#EBF2FA",
  accent: "#3B82F6",
  accentLight: "#DBEAFE",
  text: "#0F172A",
  textMuted: "#64748B",
  border: "#CBD5E1",
  bg: "#F8FAFC",
  white: "#FFFFFF",
  success: "#16A34A",
  successBg: "#DCFCE7",
  warning: "#D97706",
  warningBg: "#FEF3C7",
  danger: "#DC2626",
  dangerBg: "#FEE2E2",
};

export const S: Record<string, any> = {
  app: {
    display: "flex",
    height: "100vh",
    fontFamily: "'Inter', system-ui, sans-serif",
    background: BRAND.bg,
    fontSize: "14px",
    color: BRAND.text,
    overflow: "hidden",
  },
  sidebar: {
    width: "220px",
    minWidth: "220px",
    background: BRAND.primary,
    display: "flex",
    flexDirection: "column",
    padding: "0",
    boxShadow: "2px 0 8px rgba(0,0,0,0.15)",
    transition: "transform 0.3s ease-in-out",
  },
  sidebarMobile: (open: boolean) => ({
    position: "fixed",
    top: 0,
    left: 0,
    bottom: 0,
    width: "240px",
    background: BRAND.primary,
    display: "flex",
    flexDirection: "column",
    zIndex: 1100,
    transform: open ? "translateX(0)" : "translateX(-100%)",
    boxShadow: "4px 0 15px rgba(0,0,0,0.25)",
    transition: "transform 0.3s ease-in-out",
  } as React.CSSProperties),
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.4)",
    backdropFilter: "blur(2px)",
    zIndex: 1050,
  } as React.CSSProperties,
  logo: {
    padding: "20px 16px 16px",
    borderBottom: `1px solid rgba(255,255,255,0.1)`,
  },
  logoTitle: {
    color: "#FFFFFF",
    fontSize: "18px",
    fontWeight: "700",
    margin: 0,
    letterSpacing: "-0.3px",
  },
  logoSub: {
    color: "rgba(255,255,255,0.55)",
    fontSize: "11px",
    margin: "2px 0 0",
  },
  navList: {
    flex: 1,
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  navItem: (active: boolean) => ({
    padding: "9px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    color: active ? "#FFFFFF" : "rgba(255,255,255,0.65)",
    background: active ? "rgba(255,255,255,0.15)" : "transparent",
    fontWeight: active ? "600" : "400",
    fontSize: "13.5px",
    border: active ? "1px solid rgba(255,255,255,0.2)" : "1px solid transparent",
    transition: "all 0.15s",
    userSelect: "none",
  } as React.CSSProperties),
  sidebarFooter: {
    padding: "12px 10px",
    borderTop: `1px solid rgba(255,255,255,0.1)`,
  },
  logoutBtn: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: "8px",
    background: "rgba(239,68,68,0.15)",
    border: "1px solid rgba(239,68,68,0.3)",
    color: "#FCA5A5",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
    textAlign: "center",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    background: BRAND.white,
    borderBottom: `1px solid ${BRAND.border}`,
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    minHeight: "56px",
  },
  headerLeft: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
  },
  hmenu: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    borderRadius: "6px",
    background: BRAND.primarySurface,
    color: BRAND.primary,
    border: "none",
    cursor: "pointer",
    marginRight: "4px",
  } as React.CSSProperties,
  btnPrimary: {
    padding: "7px 14px",
    background: BRAND.primary,
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  btnSecondary: {
    padding: "7px 14px",
    background: BRAND.white,
    color: BRAND.primary,
    border: `1.5px solid ${BRAND.primaryLight}`,
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  avatar: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    background: BRAND.accentLight,
    border: `2px solid ${BRAND.accent}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "13px",
    color: BRAND.primaryLight,
    userSelect: "none",
  } as React.CSSProperties,
  content: {
    flex: 1,
    overflow: "auto",
    padding: "24px",
  },
  pageTitle: {
    fontSize: "20px",
    fontWeight: "700",
    color: BRAND.text,
    margin: "0 0 20px",
  },
  card: {
    background: BRAND.white,
    border: `1px solid ${BRAND.border}`,
    borderRadius: "12px",
    padding: "20px",
  },
  tab: (active: boolean) => ({
    padding: "7px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: active ? "600" : "400",
    background: active ? BRAND.primary : BRAND.white,
    color: active ? "#fff" : BRAND.textMuted,
    border: `1px solid ${active ? BRAND.primary : BRAND.border}`,
    userSelect: "none",
  } as React.CSSProperties),
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13.5px",
  } as React.CSSProperties,
  th: {
    background: BRAND.bg,
    padding: "10px 12px",
    textAlign: "left",
    borderBottom: `1px solid ${BRAND.border}`,
    color: BRAND.textMuted,
    fontWeight: "600",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  } as React.CSSProperties,
  td: {
    padding: "11px 12px",
    borderBottom: `1px solid ${BRAND.border}`,
    color: BRAND.text,
  },
  badge: (color: string) => ({
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "500",
    background: color === "green" ? BRAND.successBg : color === "yellow" ? BRAND.warningBg : BRAND.dangerBg,
    color: color === "green" ? BRAND.success : color === "yellow" ? BRAND.warning : BRAND.danger,
    display: "inline-block",
  } as React.CSSProperties),
  input: {
    width: "100%",
    padding: "8px 12px",
    border: `1px solid ${BRAND.border}`,
    borderRadius: "8px",
    fontSize: "13.5px",
    boxSizing: "border-box",
    background: BRAND.white,
    color: BRAND.text,
    outline: "none",
  } as React.CSSProperties,
  label: {
    fontSize: "12px",
    fontWeight: "600",
    color: BRAND.textMuted,
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    display: "block",
    marginBottom: "5px",
  } as React.CSSProperties,
  travelCard: {
    background: BRAND.white,
    border: `1px solid ${BRAND.border}`,
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  } as React.CSSProperties,
  travelCardTitle: {
    fontWeight: "600",
    fontSize: "14px",
    color: BRAND.text,
    margin: 0,
  },
  travelCardSub: {
    fontSize: "13px",
    color: BRAND.textMuted,
    margin: 0,
  },
  travelCardActions: {
    display: "flex",
    gap: "8px",
    marginTop: "4px",
  },
  btnDanger: {
    padding: "6px 12px",
    background: BRAND.dangerBg,
    color: BRAND.danger,
    border: `1px solid ${BRAND.danger}`,
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "12.5px",
    fontWeight: "500",
  },
  btnChat: {
    padding: "6px 12px",
    background: BRAND.accentLight,
    color: BRAND.primaryLight,
    border: `1px solid ${BRAND.accent}`,
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "12.5px",
    fontWeight: "500",
  },
  btnReserve: {
    padding: "6px 14px",
    background: BRAND.primary,
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "12.5px",
    fontWeight: "500",
  },
  formGroup: {
    marginBottom: "16px",
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    border: `1px solid ${BRAND.border}`,
    borderRadius: "8px",
    fontSize: "13.5px",
    background: BRAND.white,
    color: BRAND.text,
    outline: "none",
  },
  textarea: {
    width: "100%",
    padding: "8px 12px",
    border: `1px solid ${BRAND.border}`,
    borderRadius: "8px",
    fontSize: "13.5px",
    background: BRAND.white,
    color: BRAND.text,
    outline: "none",
    resize: "vertical",
    minHeight: "80px",
    boxSizing: "border-box",
    fontFamily: "inherit",
  } as React.CSSProperties,
  submitBtn: {
    width: "100%",
    padding: "10px",
    background: BRAND.primary,
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    marginTop: "4px",
  },
};
